SELECT
right(year(DATES.CALENDAR_DAY_DATE),2) || ' / ' || DATES.CALENDAR_YEAR_WEEK_NUMBER as "Calendar Week",
DATES2.CALENDAR_DAY_OF_WEEK AS "Draw Day",
to_currency_eur(MAIN_TXN.TXN_AMOUNT) AS "Net sales",
PRODUCTS.PRODUCT_NUMBER as "Product No",
PRODUCTS.PRODUCT_SHORT_DESC AS "Short Name",
MAIN_TXN.TERMINAL_NUMBER AS "Terminal No",
MAIN_TXN.CLERK_NUMBER AS "Clerk ID",
LOCATIONS.REGION_DESC AS "Regional Center",
DRAW_BASE.DRAW_COUNT AS "Count of participating draws",
MAIN_TXN.TXN_TYPE_DESC AS "Transaction Type",
MAIN_TXN.EXTERNAL_SERIAL_NUMBER_FORMATTED AS "External Serial Number",
DRAW.DRAW_INFORMATION.DATE_KEY AS "Draw CDC",
MAIN_TXN.BEGIN_DRAW_NUMBER AS "First draw numbe",
MAIN_TXN.END_DRAW_NUMBER AS "Last Draw number",
TO_CHAR(MAIN_TXN.TXN_DATE,'DD.MM.YYYY') AS "Transaction date",
MAIN_TXN.TXN_TIME AS "Transaction time"

FROM  
    TXNDTL.MAIN_TXN, 
    DIMCORE.PRODUCTS, 
    DIMCORE.LOCATIONS, 
    DIMCORE.DATES, 
    DRAW.DRAW_BASE,
    DRAW.DRAW_INFORMATION INNER JOIN
        (SELECT CALENDAR_DAY_DATE, CALENDAR_WEEK_END_DATE, DATE_KEY, CALENDAR_YEAR_WEEK_NUMBER, CALENDAR_DAY_OF_WEEK FROM DIMCORE.DATES) DATES2
        ON  DATES2.DATE_KEY = DRAW.DRAW_INFORMATION.DATE_KEY
WHERE
    MAIN_TXN.GAME_PRODUCT_KEY = DIMCORE.PRODUCTS.PRODUCT_KEY
    AND MAIN_TXN.LOCATION_KEY = LOCATIONS.LOCATION_KEY
    AND DATES.DATE_KEY=TXNDTL.MAIN_TXN.DATE_KEY
    AND DRAW.DRAW_BASE.LOCATION_KEY = LOCATIONS.LOCATION_KEY
    AND DRAW.DRAW_BASE.PRODUCT_KEY = PRODUCTS.PRODUCT_KEY
    AND DRAW.DRAW_BASE.DRAW_NUMBER = MAIN_TXN.BEGIN_DRAW_NUMBER
    AND DRAW.DRAW_INFORMATION.DRAW_INFO_KEY = DRAW.DRAW_BASE.DRAW_INFO_KEY
    AND MAIN_TXN.TERMINAL_NUMBER > 10000000
    AND PRODUCTS.PRODUCT_TYPE_CODE = 0
    AND MAIN_TXN.TXN_TYPE_CODE = 1
    AND MAIN_TXN.TXN_CANCELLED_IND = 'F'
    AND MAIN_TXN.TXN_UNDONE_IND = 'F'
    AND MAIN_TXN.TXN_REJECTED_FLAG = 'F'
    AND MAIN_TXN.TXN_DATE >= #Startdatum+date# AND MAIN_TXN.TXN_DATE <= #Enddatum+date#
    ?AND MAIN_TXN.LOCATION_NUMBER IN (#LocationNo+number#)?
    ?AND DIMCORE.LOCATIONS.REGION_CODE IN (#RegionalzentrumId+string#)?
    ?AND PRODUCTS.PRODUCT_SHORT_DESC IN (#GameShortName+string#)?

ORDER BY
DATES2.CALENDAR_WEEK_END_DATE,
DATES2.CALENDAR_DAY_DATE
-- Version: 1