SELECT
    MAIN_TXN.TXN_DATE AS TRANSACTION_DATE,
    MAIN_TXN.TXN_TIME AS TRANSACTION_TIME,
    MAIN_TXN.ENTRY_TYPE_DESC AS ENTRY_TYPE,
    MAIN_TXN.TXN_REJECTED_FLAG AS REJECTED_FLAG,
    MAIN_TXN.ERROR_DESC AS ERROR,
    MAIN_TXN.TXN_TYPE_DESC AS TRANSACTION_TYPE,
    PRODUCTS.PRODUCT_DESC AS PRODUCT_NAME,
    MAIN_TXN.EXTERNAL_SERIAL_NUMBER_FORMATTED AS SERIAL_NUMBER,
    MAIN_TXN.LOCATION_NUMBER AS RETAILER_NO,
    MAIN_TXN.TERMINAL_NUMBER AS TERMINAL_NO,
    MAIN_TXN.TXN_AMOUNT AS TRANSACTION_AMOUNT,
    MAIN_TXN.RESULT_DESC AS TRANSACTION_DATA,
    CASE MAIN_TXN.ID_CARD_NUMBER WHEN -1 THEN NULL ELSE MAIN_TXN.ID_CARD_NUMBER END AS ID_CARD
FROM
    TXNDTL.MAIN_TXN,
    DIMCORE.PRODUCTS,
    DIMCORE.LOCATIONS
WHERE
    MAIN_TXN.PRODUCT_KEY = PRODUCTS.PRODUCT_KEY
    AND MAIN_TXN.LOCATION_KEY = LOCATIONS.LOCATION_KEY
    AND MAIN_TXN.TXN_DATE >= #Startdatum+date# AND MAIN_TXN.TXN_DATE <= #Enddatum+date#
    ?AND LOCATIONS.REGION_CODE IN (#RegionalCenterNo+string#)?
    ?AND MAIN_TXN.TXN_TYPE_DESC IN (#TransactionTypes+string#)?
    ?AND MAIN_TXN.LOCATION_NUMBER IN (#AnnahmestellenNr+number#)?
    ?AND MAIN_TXN.CLERK_NUMBER IN (#KassiererNr+number#)?
    ?AND MAIN_TXN.TERMINAL_NUMBER IN (#TerminalNr+number#)?
    ?AND PRODUCTS.PRODUCT_SHORT_DESC IN (#ShortProd+string#)?
;
-- Version: 1
