SELECT
    TO_CHAR(txn.TXN_DATE,'DD.MM.YYYY') AS TRANSACTION_DATE,
    txn.TXN_TIME AS TRANSACTION_TIME,
    prd.PRODUCT_DESC AS PRODUCT_NAME,
    txn.EXTERNAL_SERIAL_NUMBER_FORMATTED AS TRANSACTION_NO,
    txn.ID_CARD_NUMBER AS CUSTOMER_CARD_NO,
    txn.LOCATION_NUMBER AS LOCATION_NO,
    loc.REGION_CODE AS REGIONAL_CENTER,
    to_currency_eur(wag.TXN_AMOUNT - wag.TICKET_CHARGE_AMOUNT) AS NET_SALE_AMOUNT,
    to_currency_eur(wag.TICKET_CHARGE_AMOUNT) AS TICKET_CHARGE,
    to_currency_eur(wag.TXN_AMOUNT) AS TOTAL_AMOUNT,
    wag.STATUS AS WAGER_STATUS
FROM
    TXNDTL.DRAW_WAGER wag
    LEFT JOIN TXNDTL.MAIN_TXN txn ON
        wag.DATE_KEY = txn.DATE_KEY AND wag.PRODUCT_NUMBER = txn.PRODUCT_NUMBER AND wag.SERIAL_NUMBER = txn.SERIAL_NUMBER
    LEFT JOIN DIMCORE.PRODUCTS prd ON
        txn.PRODUCT_KEY = prd.PRODUCT_KEY
    LEFT JOIN DIMCORE.LOCATIONS loc ON
        txn.LOCATION_KEY = loc.LOCATION_KEY
WHERE
    wag.TXN_WAG_REJECTED_FLAG = 'F'
    AND wag.TXN_CANCELLED_IND = 'F'
    AND txn.ID_CARD_NUMBER > 0
    AND txn.TXN_DATE >= #StartDate+date# AND txn.TXN_DATE <= #EndDate+date#
    ?AND txn.ID_CARD_NUMBER = #CustomerCardNo+number#?
ORDER BY
    txn.TXN_DATE,
    txn.TXN_TIME
;
