--DataSet1
SELECT TXN_DATE as DATE, TXN_TIME AS TIME, MAIN_TXN.DATE_KEY AS CDC, MAIN_TXN.LOCATION_NUMBER AS RETAILER_ID, MAIN_TXN.TERMINAL_NUMBER AS TERMINAL_ID, 
TXN_TYPE_DESC AS TRANSACTION_TYPE,COALESCE(NULLIF(UPPER(TRIM(PLAY_IT_AGAIN_IND)), 'N'), 'NA') AS PLAYITAGAIN_IND, NUMBER_OF_BOARDS AS DUR,
TO_CHAR((MAIN_TXN.TXN_AMOUNT), '$999,999,999,990.00')  AS Transaction_Amount,
EXTERNAL_SERIAL_NUMBER_FORMATTED AS TRANSACTION_EXT_SERIAL, 
TXN_REJECTED_FLAG AS REJECT_FLAG, 
ERROR_DESC AS ERROR_CODE_DESC, 
INSTANT_VALIDATION.PRODUCT_NUMBER AS INSTANT_GAME, NULLIF(INSTANT_PACK_NUMBER,-1) AS PACK, NULLIF(INSTANT_TICKET_NUMBER,-1) AS TICKET, 
NULLIF(BEGIN_DRAW_NUMBER,-1) AS FIRST_DRAW_NUMBER,
PROMO_NUMBER AS PROMO_NUMBER, 
FINANCIAL_FLAG AS UPDATE_MONEY
FROM TXNDTL.MAIN_TXN LEFT OUTER JOIN TXNDTL.PROMOTION ON
(MAIN_TXN.DATE_KEY = PROMOTION.DATE_KEY AND MAIN_TXN.SERIAL_NUMBER = PROMOTION.SERIAL_NUMBER AND MAIN_TXN.PRODUCT_NUMBER = PROMOTION.PRODUCT_NUMBER)
LEFT OUTER JOIN TXNDTL.INSTANT_VALIDATION ON
(MAIN_TXN.DATE_KEY = INSTANT_VALIDATION.DATE_KEY AND MAIN_TXN.SERIAL_NUMBER = INSTANT_VALIDATION.SERIAL_NUMBER AND MAIN_TXN.PRODUCT_NUMBER = INSTANT_VALIDATION.PRODUCT_NUMBER)
LEFT OUTER JOIN TXNDTL.DRAW_WAGER ON
(MAIN_TXN.DATE_KEY = DRAW_WAGER.DATE_KEY AND MAIN_TXN.SERIAL_NUMBER = DRAW_WAGER.SERIAL_NUMBER AND MAIN_TXN.PRODUCT_NUMBER = DRAW_WAGER.PRODUCT_NUMBER)
WHERE
 (TXNDTL.MAIN_TXN.date_key) >= (select date_key from dimcore.dates where calendar_day_date=? :: DATE ) 
and (TXNDTL.MAIN_TXN.date_key) <= (select date_key from dimcore.dates where calendar_day_date=?:: date ) 
and (TXNDTL.MAIN_TXN.GAME_PRODUCT_NUMBER in (SELECT t.VALUE::number  FROM TABLE(SPLIT_TO_TABLE(?, ',')) t  ) )
AND ( MAIN_TXN.TXN_TYPE_Code in (SELECT T.VALUE FROM TABLE(SPLIT_TO_TABLE(?,',' ))T ))

ORDER BY TXN_DATE, TXN_TIME

--Products
SELECT PRODUCT_DESC, PRODUCT_NUMBER FROM DIMCORE.PRODUCTS WHERE PRODUCT_TYPE_CODE=0

--TranTypes
SELECT CODE,DESC1 FROM DIMCORE.CODES WHERE CATEGORY LIKE '%TransactionTypes%' order by code::NUMBER